using Antlr4.Runtime;

namespace PostgreSqlInAString.Lexer {
    internal static class TokenCategorizer {
        public static SqlTokenCategory Categorize(IToken token) {
            switch (token.Type) {
                case PostgreSqlLexer.Dollar:
                case PostgreSqlLexer.OPEN_PAREN:
                case PostgreSqlLexer.CLOSE_PAREN:
                case PostgreSqlLexer.OPEN_BRACKET:
                case PostgreSqlLexer.CLOSE_BRACKET:
                case PostgreSqlLexer.COMMA:
                case PostgreSqlLexer.SEMI:
                case PostgreSqlLexer.COLON:
                case PostgreSqlLexer.STAR:
                case PostgreSqlLexer.EQUAL:
                case PostgreSqlLexer.DOT:
                case PostgreSqlLexer.PLUS:
                case PostgreSqlLexer.MINUS:
                case PostgreSqlLexer.SLASH:
                case PostgreSqlLexer.CARET:
                case PostgreSqlLexer.LT:
                case PostgreSqlLexer.GT:
                case PostgreSqlLexer.LESS_LESS:
                case PostgreSqlLexer.GREATER_GREATER:
                case PostgreSqlLexer.COLON_EQUALS:
                case PostgreSqlLexer.LESS_EQUALS:
                case PostgreSqlLexer.EQUALS_GREATER:
                case PostgreSqlLexer.GREATER_EQUALS:
                case PostgreSqlLexer.DOT_DOT:
                case PostgreSqlLexer.NOT_EQUALS:
                case PostgreSqlLexer.TYPECAST:
                case PostgreSqlLexer.PERCENT:
                case PostgreSqlLexer.PARAM:
                case PostgreSqlLexer.Operator:
                case PostgreSqlLexer.AND:
                case PostgreSqlLexer.IN_P:
                case PostgreSqlLexer.NOT:
                case PostgreSqlLexer.OR:
                case PostgreSqlLexer.ILIKE:
                case PostgreSqlLexer.IS:
                case PostgreSqlLexer.ISNULL:
                case PostgreSqlLexer.LIKE:
                case PostgreSqlLexer.NOTNULL:
                case PostgreSqlLexer.SIMILAR:
                case PostgreSqlLexer.BETWEEN:
                    return SqlTokenCategory.Operator;
                case PostgreSqlLexer.ALL:
                case PostgreSqlLexer.ANALYSE:
                case PostgreSqlLexer.ANALYZE:
                case PostgreSqlLexer.ANY:
                case PostgreSqlLexer.ARRAY:
                case PostgreSqlLexer.AS:
                case PostgreSqlLexer.ASC:
                case PostgreSqlLexer.ASYMMETRIC:
                case PostgreSqlLexer.BOTH:
                case PostgreSqlLexer.CASE:
                case PostgreSqlLexer.CAST:
                case PostgreSqlLexer.CHECK:
                case PostgreSqlLexer.COLLATE:
                case PostgreSqlLexer.COLUMN:
                case PostgreSqlLexer.CONSTRAINT:
                case PostgreSqlLexer.CREATE:
                case PostgreSqlLexer.CURRENT_CATALOG:
                case PostgreSqlLexer.CURRENT_DATE:
                case PostgreSqlLexer.CURRENT_ROLE:
                case PostgreSqlLexer.CURRENT_TIME:
                case PostgreSqlLexer.CURRENT_TIMESTAMP:
                case PostgreSqlLexer.CURRENT_USER:
                case PostgreSqlLexer.DEFAULT:
                case PostgreSqlLexer.DEFERRABLE:
                case PostgreSqlLexer.DESC:
                case PostgreSqlLexer.DISTINCT:
                case PostgreSqlLexer.DO:
                case PostgreSqlLexer.ELSE:
                case PostgreSqlLexer.EXCEPT:
                case PostgreSqlLexer.FALSE_P:
                case PostgreSqlLexer.FETCH:
                case PostgreSqlLexer.FOR:
                case PostgreSqlLexer.FOREIGN:
                case PostgreSqlLexer.FROM:
                case PostgreSqlLexer.GRANT:
                case PostgreSqlLexer.GROUP_P:
                case PostgreSqlLexer.HAVING:
                case PostgreSqlLexer.INITIALLY:
                case PostgreSqlLexer.INTERSECT:
                case PostgreSqlLexer.INTO:
                case PostgreSqlLexer.LATERAL_P:
                case PostgreSqlLexer.LEADING:
                case PostgreSqlLexer.LIMIT:
                case PostgreSqlLexer.LOCALTIME:
                case PostgreSqlLexer.LOCALTIMESTAMP:
                case PostgreSqlLexer.NULL_P:
                case PostgreSqlLexer.OFFSET:
                case PostgreSqlLexer.ON:
                case PostgreSqlLexer.ONLY:
                case PostgreSqlLexer.ORDER:
                case PostgreSqlLexer.PLACING:
                case PostgreSqlLexer.PRIMARY:
                case PostgreSqlLexer.REFERENCES:
                case PostgreSqlLexer.RETURNING:
                case PostgreSqlLexer.SELECT:
                case PostgreSqlLexer.SESSION_USER:
                case PostgreSqlLexer.SOME:
                case PostgreSqlLexer.SYMMETRIC:
                case PostgreSqlLexer.TABLE:
                case PostgreSqlLexer.THEN:
                case PostgreSqlLexer.TO:
                case PostgreSqlLexer.TRAILING:
                case PostgreSqlLexer.TRUE_P:
                case PostgreSqlLexer.UNION:
                case PostgreSqlLexer.UNIQUE:
                case PostgreSqlLexer.USER:
                case PostgreSqlLexer.USING:
                case PostgreSqlLexer.VARIADIC:
                case PostgreSqlLexer.WHEN:
                case PostgreSqlLexer.WHERE:
                case PostgreSqlLexer.WINDOW:
                case PostgreSqlLexer.WITH:
                case PostgreSqlLexer.AUTHORIZATION:
                case PostgreSqlLexer.BINARY:
                case PostgreSqlLexer.COLLATION:
                case PostgreSqlLexer.CONCURRENTLY:
                case PostgreSqlLexer.CROSS:
                case PostgreSqlLexer.CURRENT_SCHEMA:
                case PostgreSqlLexer.FREEZE:
                case PostgreSqlLexer.FULL:
                case PostgreSqlLexer.INNER_P:
                case PostgreSqlLexer.JOIN:
                case PostgreSqlLexer.LEFT:
                case PostgreSqlLexer.NATURAL:
                case PostgreSqlLexer.OUTER_P:
                case PostgreSqlLexer.OVER:
                case PostgreSqlLexer.OVERLAPS:
                case PostgreSqlLexer.RIGHT:
                case PostgreSqlLexer.VERBOSE:
                case PostgreSqlLexer.ABORT_P:
                case PostgreSqlLexer.ABSOLUTE_P:
                case PostgreSqlLexer.ACCESS:
                case PostgreSqlLexer.ACTION:
                case PostgreSqlLexer.ADD_P:
                case PostgreSqlLexer.ADMIN:
                case PostgreSqlLexer.AFTER:
                case PostgreSqlLexer.AGGREGATE:
                case PostgreSqlLexer.ALSO:
                case PostgreSqlLexer.ALTER:
                case PostgreSqlLexer.ALWAYS:
                case PostgreSqlLexer.ASSERTION:
                case PostgreSqlLexer.ASSIGNMENT:
                case PostgreSqlLexer.AT:
                case PostgreSqlLexer.ATTRIBUTE:
                case PostgreSqlLexer.BACKWARD:
                case PostgreSqlLexer.BEFORE:
                case PostgreSqlLexer.BEGIN_P:
                case PostgreSqlLexer.BY:
                case PostgreSqlLexer.CACHE:
                case PostgreSqlLexer.CALLED:
                case PostgreSqlLexer.CASCADE:
                case PostgreSqlLexer.CASCADED:
                case PostgreSqlLexer.CATALOG:
                case PostgreSqlLexer.CHAIN:
                case PostgreSqlLexer.CHARACTERISTICS:
                case PostgreSqlLexer.CHECKPOINT:
                case PostgreSqlLexer.CLASS:
                case PostgreSqlLexer.CLOSE:
                case PostgreSqlLexer.CLUSTER:
                case PostgreSqlLexer.COMMENT:
                case PostgreSqlLexer.COMMENTS:
                case PostgreSqlLexer.COMMIT:
                case PostgreSqlLexer.COMMITTED:
                case PostgreSqlLexer.CONFIGURATION:
                case PostgreSqlLexer.CONNECTION:
                case PostgreSqlLexer.CONSTRAINTS:
                case PostgreSqlLexer.CONTENT_P:
                case PostgreSqlLexer.CONTINUE_P:
                case PostgreSqlLexer.CONVERSION_P:
                case PostgreSqlLexer.COPY:
                case PostgreSqlLexer.COST:
                case PostgreSqlLexer.CSV:
                case PostgreSqlLexer.CURSOR:
                case PostgreSqlLexer.CYCLE:
                case PostgreSqlLexer.DATA_P:
                case PostgreSqlLexer.DATABASE:
                case PostgreSqlLexer.DAY_P:
                case PostgreSqlLexer.DEALLOCATE:
                case PostgreSqlLexer.DECLARE:
                case PostgreSqlLexer.DEFAULTS:
                case PostgreSqlLexer.DEFERRED:
                case PostgreSqlLexer.DEFINER:
                case PostgreSqlLexer.DELETE_P:
                case PostgreSqlLexer.DELIMITER:
                case PostgreSqlLexer.DELIMITERS:
                case PostgreSqlLexer.DICTIONARY:
                case PostgreSqlLexer.DISABLE_P:
                case PostgreSqlLexer.DISCARD:
                case PostgreSqlLexer.DOCUMENT_P:
                case PostgreSqlLexer.DOMAIN_P:
                case PostgreSqlLexer.DOUBLE_P:
                case PostgreSqlLexer.DROP:
                case PostgreSqlLexer.EACH:
                case PostgreSqlLexer.ENABLE_P:
                case PostgreSqlLexer.ENCODING:
                case PostgreSqlLexer.ENCRYPTED:
                case PostgreSqlLexer.ENUM_P:
                case PostgreSqlLexer.ESCAPE:
                case PostgreSqlLexer.EVENT:
                case PostgreSqlLexer.EXCLUDE:
                case PostgreSqlLexer.EXCLUDING:
                case PostgreSqlLexer.EXCLUSIVE:
                case PostgreSqlLexer.EXECUTE:
                case PostgreSqlLexer.EXPLAIN:
                case PostgreSqlLexer.EXTENSION:
                case PostgreSqlLexer.EXTERNAL:
                case PostgreSqlLexer.FAMILY:
                case PostgreSqlLexer.FIRST_P:
                case PostgreSqlLexer.FOLLOWING:
                case PostgreSqlLexer.FORCE:
                case PostgreSqlLexer.FORWARD:
                case PostgreSqlLexer.FUNCTION:
                case PostgreSqlLexer.FUNCTIONS:
                case PostgreSqlLexer.GLOBAL:
                case PostgreSqlLexer.GRANTED:
                case PostgreSqlLexer.HANDLER:
                case PostgreSqlLexer.HEADER_P:
                case PostgreSqlLexer.HOLD:
                case PostgreSqlLexer.HOUR_P:
                case PostgreSqlLexer.IDENTITY_P:
                case PostgreSqlLexer.IF_P:
                case PostgreSqlLexer.IMMEDIATE:
                case PostgreSqlLexer.IMMUTABLE:
                case PostgreSqlLexer.IMPLICIT_P:
                case PostgreSqlLexer.INCLUDING:
                case PostgreSqlLexer.INCREMENT:
                case PostgreSqlLexer.INDEX:
                case PostgreSqlLexer.INDEXES:
                case PostgreSqlLexer.INHERIT:
                case PostgreSqlLexer.INHERITS:
                case PostgreSqlLexer.INLINE_P:
                case PostgreSqlLexer.INSENSITIVE:
                case PostgreSqlLexer.INSERT:
                case PostgreSqlLexer.INSTEAD:
                case PostgreSqlLexer.INVOKER:
                case PostgreSqlLexer.ISOLATION:
                case PostgreSqlLexer.KEY:
                case PostgreSqlLexer.LABEL:
                case PostgreSqlLexer.LANGUAGE:
                case PostgreSqlLexer.LARGE_P:
                case PostgreSqlLexer.LAST_P:
                case PostgreSqlLexer.LEAKPROOF:
                case PostgreSqlLexer.LEVEL:
                case PostgreSqlLexer.LISTEN:
                case PostgreSqlLexer.LOAD:
                case PostgreSqlLexer.LOCAL:
                case PostgreSqlLexer.LOCATION:
                case PostgreSqlLexer.LOCK_P:
                case PostgreSqlLexer.MAPPING:
                case PostgreSqlLexer.MATCH:
                case PostgreSqlLexer.MATCHED:
                case PostgreSqlLexer.MATERIALIZED:
                case PostgreSqlLexer.MAXVALUE:
                case PostgreSqlLexer.MERGE:
                case PostgreSqlLexer.MINUTE_P:
                case PostgreSqlLexer.MINVALUE:
                case PostgreSqlLexer.MODE:
                case PostgreSqlLexer.MONTH_P:
                case PostgreSqlLexer.MOVE:
                case PostgreSqlLexer.NAME_P:
                case PostgreSqlLexer.NAMES:
                case PostgreSqlLexer.NEXT:
                case PostgreSqlLexer.NO:
                case PostgreSqlLexer.NOTHING:
                case PostgreSqlLexer.NOTIFY:
                case PostgreSqlLexer.NOWAIT:
                case PostgreSqlLexer.NULLS_P:
                case PostgreSqlLexer.OBJECT_P:
                case PostgreSqlLexer.OF:
                case PostgreSqlLexer.OFF:
                case PostgreSqlLexer.OIDS:
                case PostgreSqlLexer.OPERATOR:
                case PostgreSqlLexer.OPTION:
                case PostgreSqlLexer.OPTIONS:
                case PostgreSqlLexer.OWNED:
                case PostgreSqlLexer.OWNER:
                case PostgreSqlLexer.PARSER:
                case PostgreSqlLexer.PARTIAL:
                case PostgreSqlLexer.PARTITION:
                case PostgreSqlLexer.PASSING:
                case PostgreSqlLexer.PASSWORD:
                case PostgreSqlLexer.PLANS:
                case PostgreSqlLexer.PRECEDING:
                case PostgreSqlLexer.PREPARE:
                case PostgreSqlLexer.PREPARED:
                case PostgreSqlLexer.PRESERVE:
                case PostgreSqlLexer.PRIOR:
                case PostgreSqlLexer.PRIVILEGES:
                case PostgreSqlLexer.PROCEDURAL:
                case PostgreSqlLexer.PROCEDURE:
                case PostgreSqlLexer.PROGRAM:
                case PostgreSqlLexer.QUOTE:
                case PostgreSqlLexer.RANGE:
                case PostgreSqlLexer.READ:
                case PostgreSqlLexer.REASSIGN:
                case PostgreSqlLexer.RECHECK:
                case PostgreSqlLexer.RECURSIVE:
                case PostgreSqlLexer.REF:
                case PostgreSqlLexer.REFRESH:
                case PostgreSqlLexer.REINDEX:
                case PostgreSqlLexer.RELATIVE_P:
                case PostgreSqlLexer.RELEASE:
                case PostgreSqlLexer.RENAME:
                case PostgreSqlLexer.REPEATABLE:
                case PostgreSqlLexer.REPLACE:
                case PostgreSqlLexer.REPLICA:
                case PostgreSqlLexer.RESET:
                case PostgreSqlLexer.RESTART:
                case PostgreSqlLexer.RESTRICT:
                case PostgreSqlLexer.RETURNS:
                case PostgreSqlLexer.REVOKE:
                case PostgreSqlLexer.ROLE:
                case PostgreSqlLexer.ROLLBACK:
                case PostgreSqlLexer.ROWS:
                case PostgreSqlLexer.RULE:
                case PostgreSqlLexer.SAVEPOINT:
                case PostgreSqlLexer.SCHEMA:
                case PostgreSqlLexer.SCROLL:
                case PostgreSqlLexer.SEARCH:
                case PostgreSqlLexer.SECOND_P:
                case PostgreSqlLexer.SECURITY:
                case PostgreSqlLexer.SEQUENCE:
                case PostgreSqlLexer.SEQUENCES:
                case PostgreSqlLexer.SERIALIZABLE:
                case PostgreSqlLexer.SERVER:
                case PostgreSqlLexer.SESSION:
                case PostgreSqlLexer.SET:
                case PostgreSqlLexer.SHARE:
                case PostgreSqlLexer.SHOW:
                case PostgreSqlLexer.SIMPLE:
                case PostgreSqlLexer.SNAPSHOT:
                case PostgreSqlLexer.STABLE:
                case PostgreSqlLexer.STANDALONE_P:
                case PostgreSqlLexer.START:
                case PostgreSqlLexer.STATEMENT:
                case PostgreSqlLexer.STATISTICS:
                case PostgreSqlLexer.STDIN:
                case PostgreSqlLexer.STDOUT:
                case PostgreSqlLexer.STORAGE:
                case PostgreSqlLexer.STRICT_P:
                case PostgreSqlLexer.STRIP_P:
                case PostgreSqlLexer.SYSID:
                case PostgreSqlLexer.SYSTEM_P:
                case PostgreSqlLexer.TABLES:
                case PostgreSqlLexer.TABLESPACE:
                case PostgreSqlLexer.TEMP:
                case PostgreSqlLexer.TEMPLATE:
                case PostgreSqlLexer.TEMPORARY:
                case PostgreSqlLexer.TEXT_P:
                case PostgreSqlLexer.TRANSACTION:
                case PostgreSqlLexer.TRIGGER:
                case PostgreSqlLexer.TRUNCATE:
                case PostgreSqlLexer.TRUSTED:
                case PostgreSqlLexer.TYPE_P:
                case PostgreSqlLexer.TYPES_P:
                case PostgreSqlLexer.UNBOUNDED:
                case PostgreSqlLexer.UNCOMMITTED:
                case PostgreSqlLexer.UNENCRYPTED:
                case PostgreSqlLexer.UNKNOWN:
                case PostgreSqlLexer.UNLISTEN:
                case PostgreSqlLexer.UNLOGGED:
                case PostgreSqlLexer.UNTIL:
                case PostgreSqlLexer.UPDATE:
                case PostgreSqlLexer.VACUUM:
                case PostgreSqlLexer.VALID:
                case PostgreSqlLexer.VALIDATE:
                case PostgreSqlLexer.VALIDATOR:
                case PostgreSqlLexer.VARYING:
                case PostgreSqlLexer.VERSION_P:
                case PostgreSqlLexer.VIEW:
                case PostgreSqlLexer.VOLATILE:
                case PostgreSqlLexer.WHITESPACE_P:
                case PostgreSqlLexer.WITHOUT:
                case PostgreSqlLexer.WORK:
                case PostgreSqlLexer.WRAPPER:
                case PostgreSqlLexer.WRITE:
                case PostgreSqlLexer.XML_P:
                case PostgreSqlLexer.YEAR_P:
                case PostgreSqlLexer.YES_P:
                case PostgreSqlLexer.ZONE:
                case PostgreSqlLexer.BIGINT:
                case PostgreSqlLexer.BIT:
                case PostgreSqlLexer.BOOLEAN_P:
                case PostgreSqlLexer.CHAR_P:
                case PostgreSqlLexer.CHARACTER:
                case PostgreSqlLexer.COALESCE:
                case PostgreSqlLexer.DEC:
                case PostgreSqlLexer.DECIMAL_P:
                case PostgreSqlLexer.EXISTS:
                case PostgreSqlLexer.EXTRACT:
                case PostgreSqlLexer.FLOAT_P:
                case PostgreSqlLexer.GREATEST:
                case PostgreSqlLexer.INOUT:
                case PostgreSqlLexer.INT_P:
                case PostgreSqlLexer.INTEGER:
                case PostgreSqlLexer.INTERVAL:
                case PostgreSqlLexer.LEAST:
                case PostgreSqlLexer.NATIONAL:
                case PostgreSqlLexer.NCHAR:
                case PostgreSqlLexer.NONE:
                case PostgreSqlLexer.NULLIF:
                case PostgreSqlLexer.NUMERIC:
                case PostgreSqlLexer.OVERLAY:
                case PostgreSqlLexer.POSITION:
                case PostgreSqlLexer.PRECISION:
                case PostgreSqlLexer.REAL:
                case PostgreSqlLexer.ROW:
                case PostgreSqlLexer.SETOF:
                case PostgreSqlLexer.SMALLINT:
                case PostgreSqlLexer.SUBSTRING:
                case PostgreSqlLexer.TIME:
                case PostgreSqlLexer.TIMESTAMP:
                case PostgreSqlLexer.TREAT:
                case PostgreSqlLexer.TRIM:
                case PostgreSqlLexer.VALUES:
                case PostgreSqlLexer.VARCHAR:
                case PostgreSqlLexer.XMLATTRIBUTES:
                case PostgreSqlLexer.XMLCOMMENT:
                case PostgreSqlLexer.XMLAGG:
                case PostgreSqlLexer.XML_IS_WELL_FORMED:
                case PostgreSqlLexer.XML_IS_WELL_FORMED_DOCUMENT:
                case PostgreSqlLexer.XML_IS_WELL_FORMED_CONTENT:
                case PostgreSqlLexer.XPATH:
                case PostgreSqlLexer.XPATH_EXISTS:
                case PostgreSqlLexer.XMLCONCAT:
                case PostgreSqlLexer.XMLELEMENT:
                case PostgreSqlLexer.XMLEXISTS:
                case PostgreSqlLexer.XMLFOREST:
                case PostgreSqlLexer.XMLPARSE:
                case PostgreSqlLexer.XMLPI:
                case PostgreSqlLexer.XMLROOT:
                case PostgreSqlLexer.XMLSERIALIZE:
                case PostgreSqlLexer.CALL:
                case PostgreSqlLexer.CURRENT_P:
                case PostgreSqlLexer.ATTACH:
                case PostgreSqlLexer.DETACH:
                case PostgreSqlLexer.EXPRESSION:
                case PostgreSqlLexer.GENERATED:
                case PostgreSqlLexer.LOGGED:
                case PostgreSqlLexer.STORED:
                case PostgreSqlLexer.INCLUDE:
                case PostgreSqlLexer.ROUTINE:
                case PostgreSqlLexer.TRANSFORM:
                case PostgreSqlLexer.IMPORT_P:
                case PostgreSqlLexer.POLICY:
                case PostgreSqlLexer.METHOD:
                case PostgreSqlLexer.REFERENCING:
                case PostgreSqlLexer.NEW:
                case PostgreSqlLexer.OLD:
                case PostgreSqlLexer.VALUE_P:
                case PostgreSqlLexer.SUBSCRIPTION:
                case PostgreSqlLexer.PUBLICATION:
                case PostgreSqlLexer.OUT_P:
                case PostgreSqlLexer.END_P:
                case PostgreSqlLexer.ROUTINES:
                case PostgreSqlLexer.SCHEMAS:
                case PostgreSqlLexer.PROCEDURES:
                case PostgreSqlLexer.INPUT_P:
                case PostgreSqlLexer.SUPPORT:
                case PostgreSqlLexer.PARALLEL:
                case PostgreSqlLexer.SQL_P:
                case PostgreSqlLexer.DEPENDS:
                case PostgreSqlLexer.OVERRIDING:
                case PostgreSqlLexer.CONFLICT:
                case PostgreSqlLexer.SKIP_P:
                case PostgreSqlLexer.LOCKED:
                case PostgreSqlLexer.TIES:
                case PostgreSqlLexer.ROLLUP:
                case PostgreSqlLexer.CUBE:
                case PostgreSqlLexer.GROUPING:
                case PostgreSqlLexer.SETS:
                case PostgreSqlLexer.TABLESAMPLE:
                case PostgreSqlLexer.ORDINALITY:
                case PostgreSqlLexer.XMLTABLE:
                case PostgreSqlLexer.COLUMNS:
                case PostgreSqlLexer.XMLNAMESPACES:
                case PostgreSqlLexer.ROWTYPE:
                case PostgreSqlLexer.NORMALIZED:
                case PostgreSqlLexer.WITHIN:
                case PostgreSqlLexer.FILTER:
                case PostgreSqlLexer.GROUPS:
                case PostgreSqlLexer.OTHERS:
                case PostgreSqlLexer.NFC:
                case PostgreSqlLexer.NFD:
                case PostgreSqlLexer.NFKC:
                case PostgreSqlLexer.NFKD:
                case PostgreSqlLexer.UESCAPE:
                case PostgreSqlLexer.VIEWS:
                case PostgreSqlLexer.NORMALIZE:
                case PostgreSqlLexer.DUMP:
                case PostgreSqlLexer.PRINT_STRICT_PARAMS:
                case PostgreSqlLexer.VARIABLE_CONFLICT:
                case PostgreSqlLexer.ERROR:
                case PostgreSqlLexer.USE_VARIABLE:
                case PostgreSqlLexer.USE_COLUMN:
                case PostgreSqlLexer.ALIAS:
                case PostgreSqlLexer.CONSTANT:
                case PostgreSqlLexer.PERFORM:
                case PostgreSqlLexer.GET:
                case PostgreSqlLexer.DIAGNOSTICS:
                case PostgreSqlLexer.STACKED:
                case PostgreSqlLexer.ELSIF:
                case PostgreSqlLexer.WHILE:
                case PostgreSqlLexer.REVERSE:
                case PostgreSqlLexer.FOREACH:
                case PostgreSqlLexer.SLICE:
                case PostgreSqlLexer.EXIT:
                case PostgreSqlLexer.RETURN:
                case PostgreSqlLexer.QUERY:
                case PostgreSqlLexer.RAISE:
                case PostgreSqlLexer.SQLSTATE:
                case PostgreSqlLexer.DEBUG:
                case PostgreSqlLexer.LOG:
                case PostgreSqlLexer.INFO:
                case PostgreSqlLexer.NOTICE:
                case PostgreSqlLexer.WARNING:
                case PostgreSqlLexer.EXCEPTION:
                case PostgreSqlLexer.ASSERT:
                case PostgreSqlLexer.LOOP:
                case PostgreSqlLexer.OPEN:
                    return SqlTokenCategory.Keyword;
                case PostgreSqlLexer.ABS:
                case PostgreSqlLexer.CBRT:
                case PostgreSqlLexer.CEIL:
                case PostgreSqlLexer.CEILING:
                case PostgreSqlLexer.DEGREES:
                case PostgreSqlLexer.DIV:
                case PostgreSqlLexer.EXP:
                case PostgreSqlLexer.FACTORIAL:
                case PostgreSqlLexer.FLOOR:
                case PostgreSqlLexer.GCD:
                case PostgreSqlLexer.LCM:
                case PostgreSqlLexer.LN:
                case PostgreSqlLexer.LOG10:
                case PostgreSqlLexer.MIN_SCALE:
                case PostgreSqlLexer.MOD:
                case PostgreSqlLexer.PI:
                case PostgreSqlLexer.POWER:
                case PostgreSqlLexer.RADIANS:
                case PostgreSqlLexer.ROUND:
                case PostgreSqlLexer.SCALE:
                case PostgreSqlLexer.SIGN:
                case PostgreSqlLexer.SQRT:
                case PostgreSqlLexer.TRIM_SCALE:
                case PostgreSqlLexer.TRUNC:
                case PostgreSqlLexer.WIDTH_BUCKET:
                case PostgreSqlLexer.RANDOM:
                case PostgreSqlLexer.SETSEED:
                case PostgreSqlLexer.ACOS:
                case PostgreSqlLexer.ACOSD:
                case PostgreSqlLexer.ASIN:
                case PostgreSqlLexer.ASIND:
                case PostgreSqlLexer.ATAN:
                case PostgreSqlLexer.ATAND:
                case PostgreSqlLexer.ATAN2:
                case PostgreSqlLexer.ATAN2D:
                case PostgreSqlLexer.COS:
                case PostgreSqlLexer.COSD:
                case PostgreSqlLexer.COT:
                case PostgreSqlLexer.COTD:
                case PostgreSqlLexer.SIN:
                case PostgreSqlLexer.SIND:
                case PostgreSqlLexer.TAN:
                case PostgreSqlLexer.TAND:
                case PostgreSqlLexer.SINH:
                case PostgreSqlLexer.COSH:
                case PostgreSqlLexer.TANH:
                case PostgreSqlLexer.ASINH:
                case PostgreSqlLexer.ACOSH:
                case PostgreSqlLexer.ATANH:
                case PostgreSqlLexer.BIT_LENGTH:
                case PostgreSqlLexer.CHAR_LENGTH:
                case PostgreSqlLexer.CHARACTER_LENGTH:
                case PostgreSqlLexer.LOWER:
                case PostgreSqlLexer.OCTET_LENGTH:
                case PostgreSqlLexer.UPPER:
                case PostgreSqlLexer.ASCII:
                case PostgreSqlLexer.BTRIM:
                case PostgreSqlLexer.CHR:
                case PostgreSqlLexer.CONCAT:
                case PostgreSqlLexer.CONCAT_WS:
                case PostgreSqlLexer.FORMAT:
                case PostgreSqlLexer.INITCAP:
                case PostgreSqlLexer.LENGTH:
                case PostgreSqlLexer.LPAD:
                case PostgreSqlLexer.LTRIM:
                case PostgreSqlLexer.MD5:
                case PostgreSqlLexer.PARSE_IDENT:
                case PostgreSqlLexer.PG_CLIENT_ENCODING:
                case PostgreSqlLexer.QUOTE_IDENT:
                case PostgreSqlLexer.QUOTE_LITERAL:
                case PostgreSqlLexer.QUOTE_NULLABLE:
                case PostgreSqlLexer.REGEXP_COUNT:
                case PostgreSqlLexer.REGEXP_INSTR:
                case PostgreSqlLexer.REGEXP_LIKE:
                case PostgreSqlLexer.REGEXP_MATCH:
                case PostgreSqlLexer.REGEXP_MATCHES:
                case PostgreSqlLexer.REGEXP_REPLACE:
                case PostgreSqlLexer.REGEXP_SPLIT_TO_ARRAY:
                case PostgreSqlLexer.REGEXP_SPLIT_TO_TABLE:
                case PostgreSqlLexer.REGEXP_SUBSTR:
                case PostgreSqlLexer.REPEAT:
                case PostgreSqlLexer.RPAD:
                case PostgreSqlLexer.RTRIM:
                case PostgreSqlLexer.SPLIT_PART:
                case PostgreSqlLexer.STARTS_WITH:
                case PostgreSqlLexer.STRING_TO_ARRAY:
                case PostgreSqlLexer.STRING_TO_TABLE:
                case PostgreSqlLexer.STRPOS:
                case PostgreSqlLexer.SUBSTR:
                case PostgreSqlLexer.TO_ASCII:
                case PostgreSqlLexer.TO_HEX:
                case PostgreSqlLexer.TRANSLATE:
                case PostgreSqlLexer.UNISTR:
                case PostgreSqlLexer.AGE:
                case PostgreSqlLexer.CLOCK_TIMESTAMP:
                case PostgreSqlLexer.DATE_BIN:
                case PostgreSqlLexer.DATE_PART:
                case PostgreSqlLexer.DATE_TRUNC:
                case PostgreSqlLexer.ISFINITE:
                case PostgreSqlLexer.JUSTIFY_DAYS:
                case PostgreSqlLexer.JUSTIFY_HOURS:
                case PostgreSqlLexer.JUSTIFY_INTERVAL:
                case PostgreSqlLexer.MAKE_DATE:
                case PostgreSqlLexer.MAKE_INTERVAL:
                case PostgreSqlLexer.MAKE_TIME:
                case PostgreSqlLexer.MAKE_TIMESTAMP:
                case PostgreSqlLexer.MAKE_TIMESTAMPTZ:
                case PostgreSqlLexer.NOW:
                case PostgreSqlLexer.STATEMENT_TIMESTAMP:
                case PostgreSqlLexer.TIMEOFDAY:
                case PostgreSqlLexer.TRANSACTION_TIMESTAMP:
                case PostgreSqlLexer.TO_TIMESTAMP:
                case PostgreSqlLexer.TO_CHAR:
                case PostgreSqlLexer.TO_DATE:
                case PostgreSqlLexer.TO_NUMBER:
                    return SqlTokenCategory.SystemFunction; //  Could recognize more functions. See https://pgpedia.info/categories/system-function.html
                case PostgreSqlLexer.Parameter:
                    return SqlTokenCategory.Parameter;
                case PostgreSqlLexer.Identifier:
                case PostgreSqlLexer.QuotedIdentifier:
                case PostgreSqlLexer.UnicodeQuotedIdentifier:
                case PostgreSqlLexer.PLSQLVARIABLENAME:
                case PostgreSqlLexer.PLSQLIDENTIFIER:
                case PostgreSqlLexer.UnterminatedQuotedIdentifier:
                case PostgreSqlLexer.UnterminatedUnicodeQuotedIdentifier:
                    return SqlTokenCategory.Identifier;
                case PostgreSqlLexer.AfterEscapeStringConstantMode_NotContinued:
                case PostgreSqlLexer.AfterEscapeStringConstantWithNewlineMode_NotContinued:
                case PostgreSqlLexer.AfterEscapeStringConstantWithNewlineMode_Continued:
                case PostgreSqlLexer.BeginDollarStringConstant:
                case PostgreSqlLexer.BinaryStringConstant:
                case PostgreSqlLexer.DollarText: // TODO: retokenize dollar text string content if there is LANGUAGE plpgsql statement. Could introduce a new lexer in DollarQuotedStringMode
                case PostgreSqlLexer.EndDollarStringConstant:
                case PostgreSqlLexer.EscapeStringConstant:
                case PostgreSqlLexer.HexadecimalStringConstant:
                case PostgreSqlLexer.StringConstant:
                case PostgreSqlLexer.UnicodeEscapeStringConstant:
                case PostgreSqlLexer.UnterminatedBinaryStringConstant:
                case PostgreSqlLexer.UnterminatedEscapeStringConstant:
                case PostgreSqlLexer.UnterminatedHexadecimalStringConstant:
                case PostgreSqlLexer.UnterminatedStringConstant:
                case PostgreSqlLexer.UnterminatedUnicodeEscapeStringConstant:
                    return SqlTokenCategory.String;
                case PostgreSqlLexer.Integral:
                case PostgreSqlLexer.Numeric:
                    return SqlTokenCategory.Number;
                case PostgreSqlLexer.LineComment:
                case PostgreSqlLexer.BlockComment:
                case PostgreSqlLexer.UnterminatedBlockComment:
                    return SqlTokenCategory.Comment;
                case PostgreSqlLexer.InvalidQuotedIdentifier:
                case PostgreSqlLexer.InvalidUnterminatedQuotedIdentifier:
                case PostgreSqlLexer.InvalidUnicodeQuotedIdentifier:
                case PostgreSqlLexer.InvalidUnterminatedUnicodeQuotedIdentifier:
                case PostgreSqlLexer.InvalidBinaryStringConstant:
                case PostgreSqlLexer.InvalidEscapeStringConstant:
                case PostgreSqlLexer.InvalidHexadecimalStringConstant:
                case PostgreSqlLexer.InvalidUnterminatedBinaryStringConstant:
                case PostgreSqlLexer.InvalidUnterminatedEscapeStringConstant:
                case PostgreSqlLexer.InvalidUnterminatedHexadecimalStringConstant:
                case PostgreSqlLexer.NumericFail:
                case PostgreSqlLexer.Whitespace:
                case PostgreSqlLexer.Newline:
                case PostgreSqlLexer.MetaCommand:
                case PostgreSqlLexer.EndMetaCommand:
                case PostgreSqlLexer.ErrorCharacter:
                default:
                    return SqlTokenCategory.None;
            }
        }
    }
}
